export type FinanceRecord = Record<string, unknown> & { id?: string }

export type ResourceName =
  | 'income_sources'
  | 'expenses'
  | 'monthly_plans'
  | 'loans'
  | 'emi_payments'
  | 'credit_cards'
  | 'savings_goals'
  | 'wishlist_items'
  | 'investments'
  | 'insurance_policies'
  | 'documents'
  | 'ocr_transactions'
  | 'reminders'
  | 'family_groups'
  | 'family_members'
  | 'shared_budgets'
  | 'voice_commands'
  | 'notification_preferences'
  | 'currencies'
  | 'sync_queue'
  | 'notifications'
